config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # resources :posts
  
  resources :posts do
    member do
      post 'like', to: 'posts#like'
      delete 'unlike', to: 'posts#unlike'
    end
  end
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image ,dependent: :destroy
    has_many :likes , dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes , dependent: :destroy    
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: [:edit , :update ,:destroy, :like , :unlike]
    def index
        @post =Post.all
        @user =User.all
        @likes =Like.all
    end
    
    def new
        @post =Post.new
    end

    def create
        # @post = current_user.posts()
        @post = Post.new(post_params)
        @post.image.attach(params[:post][:image])
        if @post.save
            redirect_to posts_path ,notice: 'post sucessfully created'
        else
            render:new
        end
    end

    def edit
        
    
    end
    
    def update
        
        if @post.update(post_params)
            redirect_to posts_path,notice: 'post sucessfully updated'
        else
            render:edit
        end

    end
    
    def destroy
        @post.delete
        redirect_to posts_path,notice: 'post deleted sucessfully'
    end


    def like
        current_user.likes.create(post: @post)
        redirect_to posts_path, notice: 'Post liked!'
      end
    
      def unlike
        like = current_user.likes.find_by(post: @post)
        like.destroy if like
        redirect_to posts_path, notice: 'Post unliked!'
      end
      
    private
    def set_post
        @post = Post.find(params[:id])
    end
    
    
    def post_params
        params.require(:post).permit(:title ,:comment ,:image)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/like.html.erb
<h2>you have liked the post</h2>

app/views/posts/edit.html.erb
<h2>Update Post</h2>
<div class="add">


<%= form_for(@post, url: post_path, local: true, method: :patch) do |form| %>
    <span class="labl"><%= form.label :title, "Enter Title:" %></span>
    <span class="box"><%= form.text_field :title %></span>
    <br><br>
    <div><% if @post.image.attached? %>
        <span style="font-size: 20px;">Current Image:</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= image_tag @post.image  , size: '100x100'%>
        <% end %>
        </div>
    <br><br>
    <span class="labl2"><%= form.label :image, "Upload New Image:" %> </span>
    <span class="box2"><%= form.file_field :image , accept:'image/*' %></span>
    <br><br>
    <span class="labl3"><%= form.label :comment, "Add Comment:" %></span>
    <span class="box3"><%= form.text_field :comment %></span>
    <br><br> 
    <%= form.submit "Update Post",class: "btn-del" %>
<% end %>
</div>

app/views/posts/index.html.erb
<h2>WELCOME TO DASHBOARD </h2>
<div class="email">You now login as <span style="color:red;"> <%= current_user.email%> </div>
<div class="btn-body"><%= button_to "Logout" , destroy_user_session_path , method: :delete , class: "logout"%></span></div>
<div class="add-new-btn"><%= link_to 'Upload New Post' , new_post_path , method: :post , class: "btn"%></div>
<p style="color:green;text-align:center;font-size:20px;"><%= notice%></p>
<h3 style="color:green;">Available Posts are:</h3>

<div class="data">
    <%@post.each do |post|%>
        <div class="each-data">
            <p> <span class="data-field">Title:</span><%= post.title%></p>
            <p> <span class="data-field">Comment:</span><%= post.comment%></p>
            <% if post.image.attached?%>
                <p style="text-align:center;"><%= image_tag post.image , size: '100x100'%></p>
            <%else %>
                <p style="color:red;">image not found</p>
            <% end %>
            
            
                <p style="text-align:center;"> <%= link_to 'Update ',edit_post_path(post.id), :method => 'update', class: "btn-update"%> </p> 
                

             <%# delete button %>
            <p style="text-align:center;font-size:25px;"> <%= button_to 'Delete', post_path(post.id), :method => 'delete' , class: "btn-del"%></p>
            <%# delete button ends %>
            <%#  like functionality%>
            <% if user_signed_in?%>
                <% if current_user.likes.exists?(post: post) %>
                    <%= button_to 'Unlike', unlike_post_path(post), method: :delete , class: "btn-white"%>
                <% else %>
                    <%= button_to 'Like', like_post_path(post), method: :post , class: "btn-red"%>
                <% end %>
                <p class="like"><%= pluralize(post.likes.count, 'like') %></p>
            <% end %>
            <%#like section ends  %>
        </div>
    <%end%>
    

</div>

app/views/posts/new.html.erb
<h2>Add Post</h2>
<div class="add">
<%= form_with(model: Post.new , url: posts_path ,local: true, method: :post) do |form| %>
    <span class="labl"><%= form.label :title, "Enter Title:" %></span>
    <span class="box"><%= form.text_field :title ,:required => true%></span>
    <br><br>
    <span class="labl2"><%= form.label :image, "Upload Image:" %> </span>
    <span class="box2"><%= form.file_field :image , accept:'image/*' ,:required => true%></span>
    <br><br>
    <span class="labl3"><%= form.label :comment, "Add Comment:" %></span>
    <span class="box3"><%= form.text_field :comment ,:required => true%></span>
    <br><br> 
    <%= form.submit "Post",class: "btn-del" %>
<% end %>
</div>